# Generated by Django 3.2.5 on 2021-08-01 23:31

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210801_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
