# Generated by Django 3.2.5 on 2021-08-01 23:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210801_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='eng_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نامک دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='انتخاب دسته\u200cبندی پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='محتوای پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='منتشر شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده در تاریخ'),
        ),
    ]
