# Generated by Django 3.2.5 on 2021-08-02 00:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210802_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('content', ckeditor.fields.RichTextField(max_length=150)),
            ],
            options={
                'verbose_name': 'درباره وبلاگ',
            },
        ),
    ]
