# Generated by Django 3.2.5 on 2021-08-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_shortintro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortintro',
            options={'verbose_name': 'درباره وبلاگ', 'verbose_name_plural': 'درباره وبلاگ'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
