# Generated by Django 3.2.5 on 2021-08-03 19:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='منتشر شده در تاریخ'),
        ),
    ]
