# Generated by Django 3.2.5 on 2021-08-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortintro',
            options={},
        ),
        migrations.RemoveField(
            model_name='shortintro',
            name='content',
        ),
        migrations.RemoveField(
            model_name='shortintro',
            name='title',
        ),
    ]
