# Generated by Django 3.2.5 on 2021-08-05 10:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210805_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortintro',
            options={'verbose_name': 'درباره وبلاگ', 'verbose_name_plural': 'درباره وبلاگ'},
        ),
        migrations.AddField(
            model_name='shortintro',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shortintro',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
